### ISSUE TITLE
Hey isaac-paper

### ISSUE THREAD

**Issue by bakustarver** [fasterthanlime/dotfiles#1]
Can you send me a fresh link for your old game cause those are not working
https://web.archive.org/web/20190629124913/https://amos.me/games/paper-isaac/
I'm interested in isaac-0.4.0-linux.zip

**Comment by fasterthanlime** [comment]
Sorry, I don't have a copy of those files anymore :(

**Comment by bakustarver** [comment]
I tried to compile, but the libs are missing, maybe you still have them?

log
--
[BUILD] Preparing C files for chroot compilation...
magic-lang rock compiler 1.0.22

/home/pasha/git/isaac-paper/source/isaac.ooc:1:0 error Use not found in the ooc library path: system

To install ooc libraries, copy their directories to /usr/lib/ooc/
If you want to install libraries elsewhere, use the OOC_LIBS environment variable,
which is the path ooc will scan for .use files (in this case, system.use).
For more information, see http://ooc-lang.org/docs/tools/rock/usefiles/
-------------------




[FAIL]
make: *** [Makefile:44: rockmake] Error 1

**Comment by fasterthanlime** [comment]
I’ve also recently tried to build everything from source but even I wasn’t able to 😔
